name: interfaces
description: A set of common interfaces for Dart classes. Made mostly for internal usage.
version: 0.0.2
homepage: https://github.com/nivisi/interfaces
repository: https://github.com/nivisi/interfaces
issue_tracker: https://github.com/nivisi/interfaces/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  lint: ^1.5.3
  meta: ^1.8.0
